export const START_LOCATION = 'START_LOCATION';
export const END_LOCATION = 'END_LOCATION';
export const SHOW_GEO_ERROR = 'SHOW_GEO_ERROR';
export const CLEAR_GEO_ERROR = 'CLEAR_GEO_ERROR';

export const START_QWANT_SEARCH = 'START_QWANT_SEARCH';
export const END_QWANT_SEARCH = 'END_QWANT_SEARCH';
export const QWANT_DELETE = 'QWANT_DELETE';
export const QWANT_SELECT = 'QWANT_SELECT';
export const CHANGE_PROXY = 'CHANGE_PROXY';
export const SHOW_QWANT_ERROR = 'SHOW_QWANT_ERROR';
export const CLEAR_QWANT_ERROR = 'CLEAR_QWANT_ERROR';

export const FILL_QUIZ = 'FILL_QUIZ';
export const RUN_DISTRACTOR = 'RUN_DISTRACTOR';
export const FILL_DISTRACTOR = 'FILL_DISTRACTOR';
export const FILL_QUESTION = 'FILL_QUESTION';
export const IGNORE_QUESTION = 'IGNORE_QUESTION';
export const RUN_QUESTION = 'RUN_QUESTION';
export const RUN_QUESTIONS_LIST = 'RUN_QUESTIONS_LIST';